#!/usr/bin/env python
from more_executors import Executors

for exc in [
    Executors.sync()
    .with_map(str)
    .with_throttle()
    .with_retry()
    .with_cancel_on_shutdown(),
    Executors.sync().with_map(str).with_throttle(),
    Executors.sync().with_map(str).with_retry(),
    Executors.sync().with_map(str).with_cancel_on_shutdown(),
    Executors.thread_pool()
    .with_map(str)
    .with_retry()
    .with_throttle()
    .with_cancel_on_shutdown(),
]:
    with exc as e:
        x: str = e.submit(lambda: 123).result()
