#!/usr/bin/env python
from concurrent.futures import Future
from more_executors import Executors, SyncExecutor, MapExecutor

exc1 = Executors.sync().with_map(str)
exc2 = MapExecutor(SyncExecutor(), str)
for exc in [exc1, exc2]:
    f: Future[str] = exc.submit(lambda: 123)
    value: str = f.result()
