#!/usr/bin/env python
from concurrent.futures import Future
from more_executors import Executors
from more_executors.sync import SyncExecutor
from more_executors.map import MapExecutor


def fn1(x: int) -> str:
    return str(x)


def fn2(x: str) -> list[str]:
    return [x]


with Executors.sync().with_map(fn1).with_map(fn2) as exc:
    f: Future[list[str]] = exc.submit(lambda: 123)
    value: list[str] = f.result()
