#!/usr/bin/env python
from concurrent.futures import Future
from more_executors import (
    Executors,
    SyncExecutor,
    MapExecutor,
    PollDescriptor,
    PollExecutor,
)


def poll_to_list(ds: list[PollDescriptor[int, list[int]]]) -> None:
    for d in ds:
        d.yield_result([d.result])


with Executors.sync().with_map(int).with_poll(poll_to_list) as exc:
    f = exc.submit(lambda: "123")
    value: list[int] = f.result()
