#!/usr/bin/env python
from concurrent.futures import Future
from more_executors import (
    Executors,
    SyncExecutor,
    MapExecutor,
    PollDescriptor,
    PollExecutor,
)


def poll_to_str(ds: list[PollDescriptor[int, str]]) -> None:
    for d in ds:
        d.yield_result(str(d.result))


exc1 = Executors.sync().with_poll(poll_to_str)
exc2 = PollExecutor(SyncExecutor(), poll_to_str)
for exc in [exc1, exc2]:
    with exc as e:
        f: Future[str] = exc.submit(lambda: 123)
        value: str = f.result()
