#!/usr/bin/env python
from concurrent.futures import Future
from more_executors import Executors, SyncExecutor

for sync in [Executors.sync(), SyncExecutor()]:
    with sync as exc:
        f: Future[int] = exc.submit(lambda: 123)
        value: int = f.result()
