#!/usr/bin/env python
from concurrent.futures import Future
from more_executors import Executors, TimeoutExecutor

for exc in [
    Executors.sync().with_timeout(),
    TimeoutExecutor(Executors.sync(), 50.0),
]:
    with exc as e:
        f: int = e.submit_timeout(1.0, lambda: 123).result()

for exc2 in [
    Executors.sync().with_map(str).with_timeout(),
    # TimeoutExecutor(Executors.sync().with_map(str), 50.0),
]:
    with exc2 as e2:
        f2: str = e2.submit_timeout(1.0, lambda: 123).result()
